version: '3.7'

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    depends_on:
      - mysql
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: api-container
    expose:
      - '3001'
    ports:
      - '3001:3001'
    command: npm run dev

  mysql:
      image: mysql:8.0.21
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: root
      ports:
        - "3306:3306"     
      volumes:
        - './docker/db/data:/var/lib/mysql'
        - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
        - './docker/db/sql:/docker-entrypoint-initdb.d'
